### ISSUE TITLE
Documentation : How to setup a new DataSource ?

### ISSUE THREAD

**Issue by jruillier** [mwiede/heroku-buildpack-wildfly-mysql#1]
I'm trying to setup a new JEE project on Heroku based on Wildfly and MySQL.

Base deployment is OK with :
https://github.com/jkutner/heroku-buildpack-wildfly

I've added the JawsDB MySQL add-on and I have the mysql connection URL.

I've just added the buildpack : heroku-buildpack-wildfly-mysql

Now, how can I setup the datasource ?

**Comment by jruillier** [comment]
So far, I did it using a file MyDataSource-ds.xml in the WEB-INF directory of my webapp. 
Any better way ?

**Comment by mwiede** [comment]
This buildpack is only made to install the database driver, not the datasource itself.

Yes, you can do it via -ds.xml file or you can create your datasource via CLI. (for example, you can extend this buildpack with an additional call to jboss-cli.sh with 

`data-source add --name=DATASOURCE_NAME --jndi-name=JNDI_NAME --driver-name=DRIVER_NAME  --connection-url=CONNECTION_URL`
